### ISSUE TITLE
vxlan.remote: property is missing 

### ISSUE THREAD

**Issue by mel1nn** [nmstate/kubernetes-nmstate#695]
**What happened**:
After applying a NodeNetworkConfigurationPolicy, an error occurs: 
`libnmstate.error.NmstateLibnmError: Add profile: flannel.1 failed with error: nm-connection-error-quark: vxlan.remote: property is missing`. The flannel interface of type vxlan has not a remote value by default, is it required for nmstate to work?

The related NodeNetworkConfigurationEnactment: 
```
apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationEnactment
metadata:
  creationTimestamp: "2021-02-08T16:58:37Z"
  generation: 1
  labels:
    nmstate.io/policy: br0-eno4
  managedFields:
  - apiVersion: nmstate.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:nmstate.io/policy: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"7fa1ec81-434a-4ec3-8c28-d13ab87e6806"}:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:status:
        .: {}
        f:conditions: {}
        f:desiredState:
          .: {}
          f:interfaces: {}
        f:policyGeneration: {}
    manager: manager
    operation: Update
    time: "2021-02-08T17:00:42Z"
  name: rdev-indeedsrv004.br0-eno4
  ownerReferences:
  - apiVersion: nmstate.io/v1beta1
    kind: NodeNetworkConfigurationPolicy
    name: br0-eno4
    uid: 7fa1ec81-434a-4ec3-8c28-d13ab87e6806
  resourceVersion: "112251257"
  selfLink: /apis/nmstate.io/v1beta1/nodenetworkconfigurationenactments/rdev-indeedsrv004.br0-eno4
  uid: 1d30c45d-7991-41bd-b757-89cae1808a10
status:
  conditions:
  - lastHearbeatTime: "2021-02-08T17:00:42Z"
    lastTransitionTime: "2021-02-08T17:00:42Z"
    message: |-
      error reconciling NodeNetworkConfigurationPolicy at desired state apply: , failed to execute nmstatectl set --no-commit --timeout 480: 'exit status 1' '' '2021-02-08 17:00:42,427 root
WARNING  libnm version 1.26.7 mismatches NetworkManager version 1.22.10
      2021-02-08 17:00:42,471 root         DEBUG    Async action: Create checkpoint started
      2021-02-08 17:00:42,475 root         DEBUG    Checkpoint None created for all devices
      2021-02-08 17:00:42,475 root         DEBUG    Async action: Create checkpoint finished
      2021-02-08 17:00:42,480 root         DEBUG    Async action: Add profile: eno4 started
      2021-02-08 17:00:42,481 root         DEBUG    Async action: Add profile: flannel.1 started
      2021-02-08 17:00:42,482 root         DEBUG    Async action: Add profile: br0 started
      2021-02-08 17:00:42,484 root         DEBUG    Async action: Rollback to checkpoint /org/freedesktop/NetworkManager/Checkpoint/5 started
      2021-02-08 17:00:42,484 root         ERROR    Rollback failed with error Add profile: br0 failed with error: g-io-error-quark: Operation was cancelled (19)
      Traceback (most recent call last):
        File "/usr/bin/nmstatectl", line 11, in <module>
          load_entry_point('nmstate==0.3.6', 'console_scripts', 'nmstatectl')()
        File "/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 69, in main
          return args.func(args)
        File "/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 279, in apply
          args.save_to_disk,
        File "/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 308, in apply_state
          save_to_disk=save_to_disk,
        File "/usr/lib/python3.6/site-packages/libnmstate/netapplier.py", line 71, in apply
          _apply_ifaces_state(plugins, net_state, verify_change, save_to_disk)
        File "/usr/lib/python3.6/site-packages/libnmstate/netapplier.py", line 104, in _apply_ifaces_state
          plugin.apply_changes(net_state, save_to_disk)
        File "/usr/lib/python3.6/site-packages/libnmstate/nm/plugin.py", line 178, in apply_changes
          nm_applier.apply_changes(self.context, net_state, save_to_disk)
        File "/usr/lib/python3.6/site-packages/libnmstate/nm/applier.py", line 152, in apply_changes
          context.wait_all_finish()
        File "/usr/lib/python3.6/site-packages/libnmstate/nm/context.py", line 216, in wait_all_finish
          raise tmp_error
      libnmstate.error.NmstateLibnmError: Add profile: flannel.1 failed with error: nm-connection-error-quark: vxlan.remote: property is missing (6)
      '
    reason: FailedToConfigure
    status: "True"
    type: Failing
  - lastHearbeatTime: "2021-02-08T17:00:42Z"
    lastTransitionTime: "2021-02-08T17:00:42Z"
    reason: FailedToConfigure
    status: "False"
    type: Available
  - lastHearbeatTime: "2021-02-08T17:00:42Z"
    lastTransitionTime: "2021-02-08T17:00:42Z"
    reason: FailedToConfigure
    status: "False"
    type: Progressing
  - lastHearbeatTime: "2021-02-08T16:58:37Z"
    lastTransitionTime: "2021-02-08T16:58:37Z"
    message: All policy selectors are matching the node
    reason: AllSelectorsMatching
    status: "True"
    type: Matching
  - lastHearbeatTime: "2021-02-08T17:00:42Z"
    lastTransitionTime: "2021-02-08T17:00:42Z"
    reason: SuccessfullyConfigured
    status: "False"
    type: Aborted
  desiredState:
    interfaces:
    - bridge:
        options:
          stp:
            enabled: false
        port:
        - name: eno4
      description: Linux bridge with eno4 as a port
      name: br0
      state: up
      type: linux-bridge
  policyGeneration: 1
```

**Comment by qinqon** [comment]
What NetworkManager version do you have at the nodes ?

**Comment by mel1nn** [comment]
1.22.10

**Comment by qinqon** [comment]
What os are you running at nodes ?

**Comment by mel1nn** [comment]
Ubuntu 20.04 !

**Comment by phoracek** [comment]
Quique please keep me honest here, but this seems to be a bug of underlying nmstate component. Seems that it is unable to handle the configuration when VXLAN interfaces are present on the host. Would you please open an issue on https://github.com/nmstate/nmstate? kubernetes-nmstate is just a way to deploy nmstate on Kubernetes.

**Comment by qinqon** [comment]
@phoracek yep, just gathering some info for them here.

**Comment by qinqon** [comment]
Well I have an answer from NetworkManager team it was mandatory until ` 676fe327d4c1fe0d11dae41b39e232ea64f4e1ea (1.29.1)`

@mel1nn can you bump network manager to > 1.29.1 ?

**Comment by phoracek** [comment]
Mandatory to define when you are configuring a VXLAN. That is not the case here. IIUIC the problem we see here is that nmstate again fails because of it cannot parse the state unrelated to the configuration we are trying to setup.

**Comment by qinqon** [comment]
@phoracek right, I supose the `eno4` has nothing to do with flannel isn't it @mel1nn

**Comment by mel1nn** [comment]
yes, that's right

**Comment by phoracek** [comment]
@mel1nn please open an issue directly on nmstate/nmstate then. I'm afraid there is nothing we could fix here - we need to fix the root cause.
